#!/bin/sh


# Cleanup previous build files
rm -rf obj_dir
rm -f Auto_f1.vcd

verilator -Wall --cc --trace Auto_f1.sv clktick.sv f1_fsm.sv --exe Auto_f1_tb.cpp --top-module Auto_f1

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VAuto_f1.mk VAuto_f1

# Run the executable simulation file
obj_dir/VAuto_f1

