#!/bin/sh


# Cleanup previous build files
rm -rf obj_dir
rm -f f1_fsm.vcd

verilator -Wall --cc --trace f1_fsm.sv --exe f1_fsm_tb.cpp 

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_fsm.mk Vf1_fsm

# Run the executable simulation file
obj_dir/Vf1_fsm

